services:
  - type: web
    name: outline-vpn
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    docker:
      args:
        NODE_IMAGE: node:16-buster-slim
